
version: v2.0
name: "build and test"
 
on:
  mr: 
    target-branches:
      - master
 
stages:
  - name: "linux"
    jobs: 
      job_MacOS:
        name: "MacOS Build & Test"
        runs-on: macos-latest
        steps: 
          - name: "checkout"
            checkout: self

          - name: "build" 
            run: |-
              #!/bin/bash
              /usr/local/go/bin/go build ./...
          
          - name: "test"
          