
version: v2.0
name: "build and test"
 
on:
  mr: 
    target-branches:
      - master
 
stages:
  - name: "mr"
    jobs: 
      job:
        steps: 
          - name: "install golang"
            run: |-
              #!/bin/bash
              if command -v go &> /dev/null; then
                go_version=$(go version)
                echo "Go is installed. Version: $go_version"
              else
                echo "Go is not installed. Install now"
                export PATH=$PATH:/usr/local/go/bin
                go version
              fi

          - name: "checkout"
            checkout: self

          - name: "build" 
            run: |-
              #!/bin/bash
              go build ./...
          
          - name: "test"
            run: |-
              #!/bin/bash
              go test ./...
          