
version: v2.0
name: "build and test"
 
on:
  mr: 
    target-branches:
      - master
 
stages:
  - name: "mr"
    jobs: 
      job:
        steps: 
          - name: "install golang"
            run: |-
              #!/bin/bash
              if command -v go &> /dev/null; then
                go_version=$(go version)
                echo "Go is installed. Version: $go_version"
              else
                echo "Go is not installed. Install now"
                install_go_version=go1.20.4.linux-amd64
                wget https://go.dev/dl/$install_go_version.tar.gz
                rm -rf /usr/local/go && tar -C /usr/local -xzf $install_go_version.tar.gz

                # Add the path of Go to the user's configuration file.
                echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
                echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile

                # Update the PATH of the current shell session immediately.
                export PATH=$PATH:/usr/local/go/bin
                go version
              fi

          - name: "checkout"
            checkout: self

          - name: "build" 
            run: |-
              #!/bin/bash
              go build ./...
          
          - name: "test"
            run: |-
              #!/bin/bash
              go test ./...
          